environments:
  stable:
    phone: "15274438093"
    signature: "stable自动化签名"
    template: "stable自动化测试模板"
    company: "上海木南信息科技有限公司"
    constant_template: "stable自动化常量模板发送测试"
    variable_template: "stable自动化变量模板发送测试{s}"
    smart_audit_signature_url: "http://smart-operation-dev.cm253.com/child-risk/review/sign-apply"
    smart_audit_template_url: "http://smart-operation-dev.cm253.com/child-risk/review/text-tem"
    smart_signature_subport_url: "http://smart-operation-dev.cm253.com/child-resource/pass-support/subport"
    create_signature_url: "http://172.16.41.223:9999/new-control/nation/domestic-signature/add?app_key=cl_yzm_sms"
    create_template_url: "http://172.16.41.223:9999/new-control/nation/domestic-template/add?app_key=cl_yzm_sms"
    constant_send_url: "http://172.16.41.223:9999/new-control/nation/domestic-send/constant?app_key=cl_yzm_sms"
    variable_send_url: "http://172.16.41.223:9999/new-control/nation/domestic-send/variable?app_key=cl_yzm_sms"
    send_records_url: "http://172.16.41.223:9999/new-control/nation/domestic-data-center/records?tab=send"
    template_url: "http://172.16.41.223:9999/new-control/nation/domestic-template"
    assert_constant_template: "【创蓝云智】stable自动化常量模板发送测试"
    assert_variable_template: "【创蓝云智】stable自动化变量模板发送测试测试"
  sit:
    phone: "15274438093"
    signature: "sit自动化签名"
    template: "sit自动化测试模板"
    company: "青岛利盛润食品有限公司"
    constant_template: "sit自动化常量模板发送测试"
    variable_template: "sit自动化变量模板发送测试{s}"
    smart_audit_signature_url: "http://smart-operation-sit.cm253.com/child-risk/review/sign-apply"
    smart_audit_template_url: "http://smart-operation-sit.cm253.com/child-risk/review/text-tem"
    smart_signature_subport_url: "http://smart-operation-sit.cm253.com/child-resource/pass-support/subport"
    create_signature_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/signature"
    create_template_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/template"
    constant_send_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/onlineSend"
    variable_send_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/variableSend"
    send_records_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/send-records"
    assert_constant_template: "【创蓝云智】sit自动化常量模板发送测试拒收请回复R"
    assert_variable_template: "【创蓝云智】sit自动化变量模板发送测试测试拒收请回复R"
  prod:
    phone: "15274438093"
    signature: "prod自动化测试签名"
    template: "prod自动化测试模板"
    company: "长沙世界之窗有限公司"
    constant_template: "prod自动化常量模板发送测试"
    variable_template: "prod自动化变量模板发送测试{s}"
    smart_audit_signature_url: "https://smart-operation.new253.com/child-risk/review/sign-apply"
    smart_audit_template_url: "https://smart-operation.new253.com/child-risk/review/text-tem"
    smart_signature_subport_url: "https://smart-operation.new253.com/child-resource/pass-support/subport"
    create_signature_url: "https://www.chuanglan.com/control/sms/cl_market_sms/signature"
    create_template_url: "https://www.chuanglan.com/control/sms/cl_market_sms/template"
    constant_send_url: "https://www.chuanglan.com/control/sms/cl_market_sms/onlineSend"
    variable_send_url: "https://www.chuanglan.com/control/sms/cl_market_sms/variableSend"
    send_records_url: "https://www.chuanglan.com/control/sms/cl_market_sms/send-records"
    assert_constant_template: "【创蓝云智】prod自动化常量模板发送测试拒收请回复R"
    assert_variable_template: "【创蓝云智】prod自动化变量模板发送测试测试拒收请回复R"
