environments:
  sit:
    phone: "15274438093"
    signature: "sit自动化测试签名"
    template: "sit自动化测试模板"
    company: "深圳市天视通技术有限公司"
    constant_template: "sit自动化常量模板发送测试"
    variable_template: "sit自动化变量模板发送测试{s}"
    smart_audit_signature_url: "http://smart-operation-sit.cm253.com/child-risk/review/sign-apply"
    create_signature_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/signature"
    create_template_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/template"
    constant_send_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/onlineSend"
    variable_send_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/variableSend"
    send_records_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/send-records"
    assert_constant_template: "【创蓝云智】sit自动化常量模板发送测试拒收请回复R"
    assert_variable_template: "【创蓝云智】sit自动化变量模板发送测试测试拒收请回复R"
  prod:
    phone: "15274438093"
    signature: "prod自动化测试签名"
    template: "prod自动化测试模板"
    company: "长沙世界之窗有限公司"
    constant_template: "prod自动化常量模板发送测试"
    variable_template: "prod自动化变量模板发送测试{s}"
    smart_audit_signature_url: "http://smart-operation.newcm253.com/child-risk/review/sign-apply"
    create_signature_url: "https://www.chuanglan.com/control/sms/cl_market_sms/signature"
    create_template_url: "https://www.chuanglan.com/control/sms/cl_market_sms/template"
    constant_send_url: "https://www.chuanglan.com/control/sms/cl_market_sms/onlineSend"
    variable_send_url: "https://www.chuanglan.com/control/sms/cl_market_sms/variableSend"
    send_records_url: "https://www.chuanglan.com/control/sms/cl_market_sms/send-records"
    assert_constant_template: "【创蓝云智】prod自动化常量模板发送测试拒收请回复R"
    assert_variable_template: "【创蓝云智】prod自动化变量模板发送测试测试拒收请回复R"
